baseURL = 'https://QinLangT.github.io/'
languageCode = 'zh-cn'
title = 'WizardLang's 技术博客'
theme = 'PaperMod'

[params]
  author = 'WizardLang'
  description = '分享密码技术'
  env = 'production'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = 'auto'

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '文章'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = '关于'
    url = '/about/'
    weight = 3
